name: food_zone
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  get: ^4.6.6
  http: ^1.2.2
  lottie: ^3.2.0
  solar_icons: ^0.0.5
  shared_preferences: ^2.3.4
  flutter_hooks: ^0.20.5
  pinput: ^5.0.0
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  auto_scroll_text: ^0.0.7
  custom_refresh_indicator: ^4.0.1
  intl: ^0.20.2
  image_cropper: ^8.1.0
  flutter_local_notifications: ^19.2.1
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  flutter_slidable: ^3.1.2
  pushy_flutter: ^2.0.30
  flutter_stripe: ^11.4.0
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  google_sign_in: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/promotion/
    - assets/icons/social/
    - assets/lottie/
    - assets/map/dark.json
    - assets/map/light.json

  fonts:
    - family: SFText
      fonts:
        - asset: assets/fonts/en/SFUIText-Light.woff
          weight: 300
        - asset: assets/fonts/en/SFUIText-Regular.woff
          weight: 400
        - asset: assets/fonts/en/SFUIText-Medium.woff
          weight: 500
        - asset: assets/fonts/en/SFUIText-Semibold.woff
          weight: 600
        - asset: assets/fonts/en/SFUIText-Bold.woff
          weight: 700

    - family: SFArabic
      fonts:
        - asset: assets/fonts/ar/SFArabicRounded-Regular.woff
